<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Remove the entry meta in the entry header (requires HTML5 theme support)
remove_action( 'genesis_entry_header', 'genesis_post_info', 12 );

add_action( 'genesis_entry_header', 'saint_death' );
function saint_death() {
	$death = get_field( 'saint_birthdate' );
	if ( ! empty( $death ) ) {
		?>
        <span class="saint-death">(+<?php echo $death; ?>)</span>
		<?php
	}
}

add_action( 'genesis_entry_header', 'saint_date' );
function saint_date() {
	$date = get_field( 'saint_date' );
	if ( ! empty( $date ) ) {
		$month = substr( $date, 0, 2 );
		$day   = substr( $date, 2, 2 );

		switch ( $month ) {
			case ( '01' ):
				$month = "fanvier";
				break;

			case ( '02' ):
				$month = "février";
				break;

			case ( '03' ):
				$month = "mars";
				break;

			case ( '04' ):
				$month = "avril";
				break;

			case ( '05' ):
				$month = "mai";
				break;

			case ( '06' ):
				$month = "juin";
				break;

			case ( '07' ):
				$month = "juillet";
				break;

			case ( '08' ):
				$month = "Aout";
				break;

			case ( '09' ):
				$month = "septembre";
				break;

			case ( '10' ):
				$month = "octobre";
				break;

			case ( '11' ):
				$month = "novembre";
				break;

			case ( '12' ):
				$month = "décembre";
				break;
		}

		?>
        <p>Saint fêté le <?php echo $day . ' ' . $month; ?>.</p>
	<?php }
}

add_action( 'genesis_entry_footer', 'saint_other' );
function saint_other() {

	$date = get_field( 'saint_date' );

	//var_dump($cur_date);

	// WP_Query arguments
	$currentID = get_the_ID();
	//var_dump($currentID);
	$args = array(
		'post_type'  => array( 'saint' ),
		'meta_query' => array(
			array(
				'key'     => 'saint_date',
				'value'   => $date,
				'compare' => '=',
				'type'    => 'CHAR',
			),
		),
		'post__not_in' => array($currentID),
	);

// The Query
	$query = new WP_Query( $args );
	$nb_st = $query->post_count;
	//var_dump($nb_st);
	if ( $nb_st >= 1 ) {
		if ( ! empty( $date ) ) {
			$month = substr( $date, 0, 2 );
			$day   = substr( $date, 2, 2 );

			switch ( $month ) {
				case ( '01' ):
					$month = "fanvier";
					break;

				case ( '02' ):
					$month = "février";
					break;

				case ( '03' ):
					$month = "mars";
					break;

				case ( '04' ):
					$month = "avril";
					break;

				case ( '05' ):
					$month = "mai";
					break;

				case ( '06' ):
					$month = "juin";
					break;

				case ( '07' ):
					$month = "juillet";
					break;

				case ( '08' ):
					$month = "Aout";
					break;

				case ( '09' ):
					$month = "septembre";
					break;

				case ( '10' ):
					$month = "octobre";
					break;

				case ( '11' ):
					$month = "novembre";
					break;

				case ( '12' ):
					$month = "décembre";
					break;
			}
		}

		$display = 'Fêter aussi le ' . $day . ' ' . $month . ' : ';
		if ( $query->have_posts() ) {
		    $i = 1;
			while ( $query->have_posts() ) {
				$query->the_post();
				if ($i != $nb_st) {
					$display .= '<a href=" ' . get_the_permalink() . ' " >' . get_the_title() . ' </a> - ';
				} else {
					$display .= '<a href=" ' . get_the_permalink() . ' " >' . get_the_title() . ' </a>.';
                }
                $i++;
			}
		}
		echo $display;
	}
}

//* This file handles single entries, but only exists for the sake of child theme forward compatibility.
genesis();
